# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Estefy\Documents\Notarius2.0\Notarius\ui\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QDialog(object):
    def setupUi(self, QDialog):
        QDialog.setObjectName("QDialog")
        QDialog.resize(1200, 800)
        QDialog.setStyleSheet("QDialog {\n"
" background-color:rgb(255, 253, 225);\n"
" \n"
" }")
        self.gridLayout = QtWidgets.QGridLayout(QDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(QDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.vertabla = VerTabla()
        self.vertabla.setObjectName("vertabla")
        self.stackedWidget.addWidget(self.vertabla)
        self.agregar = AgregarRegistro()
        self.agregar.setObjectName("agregar")
        self.stackedWidget.addWidget(self.agregar)
        self.editarprivilegios = EditarPrivilegios()
        self.editarprivilegios.setObjectName("editarprivilegios")
        self.stackedWidget.addWidget(self.editarprivilegios)
        self.registrarusuario = RegistrarUsuario()
        self.registrarusuario.setWhatsThis("")
        self.registrarusuario.setObjectName("registrarusuario")
        self.stackedWidget.addWidget(self.registrarusuario)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(QDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.botonTabla = QtWidgets.QPushButton(QDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.botonTabla.setFont(font)
        self.botonTabla.setAutoFillBackground(False)
        self.botonTabla.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"    height: 25px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Estefy\\Documents\\Notarius2.0\\Notarius\\ui\\bar-chart-box-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonTabla.setIcon(icon)
        self.botonTabla.setAutoDefault(False)
        self.botonTabla.setFlat(False)
        self.botonTabla.setObjectName("botonTabla")
        self.verticalLayout_6.addWidget(self.botonTabla)
        self.pushButton_6 = QtWidgets.QPushButton(QDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Estefy\\Documents\\Notarius2.0\\Notarius\\ui\\file-history-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_9 = QtWidgets.QPushButton(QDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Estefy\\Documents\\Notarius2.0\\Notarius\\ui\\file-excel-2-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_6.addWidget(self.pushButton_9)
        self.botonAgregar = QtWidgets.QPushButton(QDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.botonAgregar.setFont(font)
        self.botonAgregar.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Estefy\\Documents\\Notarius2.0\\Notarius\\ui\\profile-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonAgregar.setIcon(icon3)
        self.botonAgregar.setObjectName("botonAgregar")
        self.verticalLayout_6.addWidget(self.botonAgregar)
        self.botonRegistrar = QtWidgets.QPushButton(QDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.botonRegistrar.setFont(font)
        self.botonRegistrar.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botonRegistrar.setObjectName("botonRegistrar")
        self.verticalLayout_6.addWidget(self.botonRegistrar)
        self.pushButton_eliminar_usuario = QtWidgets.QPushButton(QDialog)
        self.pushButton_eliminar_usuario.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"height: 25px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_eliminar_usuario.setObjectName("pushButton_eliminar_usuario")
        self.verticalLayout_6.addWidget(self.pushButton_eliminar_usuario)
        self.botonEditarPrivilegios = QtWidgets.QPushButton(QDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.botonEditarPrivilegios.setFont(font)
        self.botonEditarPrivilegios.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Estefy\\Documents\\Notarius2.0\\Notarius\\ui\\edit-2-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonEditarPrivilegios.setIcon(icon4)
        self.botonEditarPrivilegios.setObjectName("botonEditarPrivilegios")
        self.verticalLayout_6.addWidget(self.botonEditarPrivilegios)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.pushButton = QtWidgets.QPushButton(QDialog)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(141, 110, 58);\n"
"    border: none;\n"
"height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(149, 117, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Estefy\\Documents\\Notarius2.0\\Notarius\\ui\\logout-box-r-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem8)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(QDialog)
        QtCore.QMetaObject.connectSlotsByName(QDialog)

    def retranslateUi(self, QDialog):
        _translate = QtCore.QCoreApplication.translate
        QDialog.setWindowTitle(_translate("QDialog", "MainWindow"))
        self.label_2.setText(_translate("QDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:24pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt; color:rgb(141, 110, 58);\">Notarius</span></p></body></html>"))
        self.botonTabla.setText(_translate("QDialog", "Tabla"))
        self.pushButton_6.setText(_translate("QDialog", "Historial"))
        self.pushButton_9.setText(_translate("QDialog", "Importar Excel"))
        self.botonAgregar.setText(_translate("QDialog", "Agregar Registro"))
        self.botonRegistrar.setText(_translate("QDialog", "Agregar Usuario"))
        self.pushButton_eliminar_usuario.setWhatsThis(_translate("QDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Eliminar Usuario</span></p><p><br/></p></body></html>"))
        self.pushButton_eliminar_usuario.setText(_translate("QDialog", "Eliminar Usuario"))
        self.botonEditarPrivilegios.setText(_translate("QDialog", "Editar Privilegios"))
        self.pushButton.setText(_translate("QDialog", "Cerrar Sesión"))
from pages.agregar import AgregarRegistro
from pages.editarprivilegios import EditarPrivilegios
from pages.registrarusuario import RegistrarUsuario
from pages.vertabla import VerTabla
