# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Estefy\Documents\Notarius2.0\Notarius\ui\editar-registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 847)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(100, 12, 100, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(141, 110, 58);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_id = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_id.setFont(font)
        self.label_id.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";\n"
"color: rgb(141, 110, 58);")
        self.label_id.setObjectName("label_id")
        self.verticalLayout_2.addWidget(self.label_id)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"border-radius: 6px;\n"
"border: 1px solid #d3c393;\n"
"background-color: white;\n"
"color:  #95753d;\n"
"height: 20px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";\n"
"color: rgb(141, 110, 58);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"border-radius: 6px;\n"
"border: 1px solid #d3c393;\n"
"background-color: white;\n"
"color:  #95753d;\n"
"height: 20px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 14pt \"Arial Rounded MT\";\n"
"color: rgb(141, 110, 58);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";\n"
"color: rgb(141, 110, 58);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"border-radius: 6px;\n"
"border: 1px solid #d3c393;\n"
"background-color: white;\n"
"color:  #95753d;\n"
"height: 20px;\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";\n"
"color: rgb(141, 110, 58);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"border-radius: 6px;\n"
"border: 1px solid #d3c393;\n"
"background-color: white;\n"
"color:  #95753d;\n"
"height: 20px;\n"
"}")
        self.lineEdit_2.setMaxLength(2000)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";\n"
"color: rgb(141, 110, 58);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"border-radius: 6px;\n"
"border: 1px solid #d3c393;\n"
"background-color: white;\n"
"color:  #95753d;\n"
"height: 20px;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";\n"
"color: rgb(141, 110, 58);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_cancel = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_cancel.setFont(font)
        self.button_cancel.setStyleSheet("QPushButton {\n"
"border-radius: 6px;\n"
"border: 2px solid #95753d;\n"
"background-color: white;\n"
"color: #95753d;\n"
"height: 25px;\n"
"padding: 2px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(116, 91, 47);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(116, 91, 47);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(103, 80, 41);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(103, 80, 41);\n"
"}")
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_4.addWidget(self.button_cancel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.button_guardar = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_guardar.setFont(font)
        self.button_guardar.setStyleSheet("QPushButton {\n"
"border-radius: 6px;\n"
"border: 3px solid #95753d;\n"
"background-color: #95753d;\n"
"color: white;\n"
"height: 25px;\n"
"padding: 2px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(116, 91, 47);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(116, 91, 47);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(103, 80, 41);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(103, 80, 41);\n"
"}")
        self.button_guardar.setObjectName("button_guardar")
        self.horizontalLayout_4.addWidget(self.button_guardar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Editar Registro"))
        self.label_id.setText(_translate("Form", "ID"))
        self.label_5.setText(_translate("Form", "Input"))
        self.label_6.setText(_translate("Form", "Your password is between 4 and 12 characters"))
        self.label_9.setText(_translate("Form", "Input"))
        self.label_4.setText(_translate("Form", "Input"))
        self.label_7.setText(_translate("Form", "Input Text Label"))
        self.label_8.setText(_translate("Form", "Error message informing me of a problem"))
        self.button_cancel.setText(_translate("Form", "Cancelar"))
        self.button_guardar.setText(_translate("Form", " Guardar"))
