# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Estefy\Documents\Notarius2.0\Notarius\ui\eliminar-usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 501)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(100, -1, 100, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_editar_privilegios = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_editar_privilegios.setFont(font)
        self.label_editar_privilegios.setStyleSheet("color: rgb(149, 117, 61);")
        self.label_editar_privilegios.setAlignment(QtCore.Qt.AlignCenter)
        self.label_editar_privilegios.setObjectName("label_editar_privilegios")
        self.verticalLayout.addWidget(self.label_editar_privilegios)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usuarioslist = QtWidgets.QComboBox(Form)
        self.usuarioslist.setStyleSheet("\n"
"font: 16pt \"\";\n"
"color: rgb(149, 117, 61);")
        self.usuarioslist.setObjectName("usuarioslist")
        self.gridLayout.addWidget(self.usuarioslist, 2, 0, 1, 1)
        self.label_Usuarios = QtWidgets.QLabel(Form)
        self.label_Usuarios.setStyleSheet("\n"
"font: 20pt \"\";\n"
"color: rgb(149, 117, 61);")
        self.label_Usuarios.setObjectName("label_Usuarios")
        self.gridLayout.addWidget(self.label_Usuarios, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_eliminar_usuario = QtWidgets.QPushButton(Form)
        self.pushButton_eliminar_usuario.setStyleSheet("QPushButton {\n"
"border-radius: 6px;\n"
"border: 3px solid #95753d;\n"
"background-color: #95753d;\n"
"color: white;\n"
"height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(116, 91, 47);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(116, 91, 47);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(103, 80, 41);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(103, 80, 41);\n"
"}")
        self.pushButton_eliminar_usuario.setObjectName("pushButton_eliminar_usuario")
        self.verticalLayout.addWidget(self.pushButton_eliminar_usuario)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button_guardar = QtWidgets.QPushButton(Form)
        self.button_guardar.setStyleSheet("QPushButton {\n"
"border-radius: 6px;\n"
"border: 3px solid #95753d;\n"
"background-color: #95753d;\n"
"color: white;\n"
"height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(116, 91, 47);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(116, 91, 47);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(103, 80, 41);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid  rgb(103, 80, 41);\n"
"}")
        self.button_guardar.setObjectName("button_guardar")
        self.verticalLayout.addWidget(self.button_guardar)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_editar_privilegios.setText(_translate("Form", "Eliminar Usuario"))
        self.label_Usuarios.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Usuarios</span></p></body></html>"))
        self.pushButton_eliminar_usuario.setText(_translate("Form", "Eliminar"))
        self.button_guardar.setText(_translate("Form", "    Guardar    "))
